# Generated by Django 5.2.17 on 2026-10-01 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], max_length=2)),
                ('stage', models.CharField(choices=[('predeparture', 'Before you fly')], default='predeparture', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('body', models.TextField(help_text='Plain text. Separate paragraphs with blank lines.')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of objects with title and url. Approved official HTTPS hosts only.')),
                ('checklist_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Sample content can never be published.')),
                ('verified_on', models.DateField(blank=True, help_text='Actual human review date; never a build date.', null=True)),
                ('next_review_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'language'), name='unique_guide_language')],
            },
        ),
    ]
