import { navigateSidebar } from './navigation';
import { test, expect } from '@playwright/test';
test('first-week reviewed guide retains language, isolated saved copies and task progress offline',async({page,context},testInfo)=>{
  await page.goto('/#/guides/test-documents');
  await page.getByRole('button',{name:'Save guide',exact:true}).click();
  const oldRecord=await page.evaluate(()=>localStorage.getItem('sajilo-nz.saved-guides.v1'));
  await navigateSidebar(page, 'First-week checklist');
  await page.getByRole('link',{name:'Browse first-week guides',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Settle in, one step at a time'})).toBeVisible();
  await expect(page.getByRole('link',{name:'Test travel documents',exact:true})).toHaveCount(0);
  await page.getByLabel('Guide language / भाषा').selectOption('ne');
  await expect(page.getByRole('link',{name:'परीक्षण पहिलो हप्ताको यात्रा',exact:true})).toBeVisible();
  await expect(page.getByText('Unreviewed arrival translation')).toHaveCount(0);
  await page.getByRole('link',{name:'परीक्षण पहिलो हप्ताको यात्रा',exact:true}).click();
  await expect(page.locator('article.guide-body')).toHaveAttribute('lang','ne');
  const date=await page.locator('article.guide-body time').first().getAttribute('datetime');
  await page.getByRole('button',{name:'Save guide',exact:true}).click();
  expect(await page.evaluate(()=>localStorage.getItem('sajilo-nz.saved-guides.v1'))).toBe(oldRecord);
  await expect(page.locator('.offline-status')).toHaveAttribute('data-offline-ready','true');
  await page.screenshot({path:testInfo.outputPath('firstweek-guide.png'),fullPage:true});
  await context.setOffline(true);await page.reload();
  await expect(page.getByText('Showing saved copies only.',{exact:false})).toBeVisible();
  await expect(page.locator('article.guide-body time').first()).toHaveAttribute('datetime',date!);
  await page.getByRole('link',{name:'Plan a local journey',exact:true}).click();
  const task=page.getByRole('checkbox',{name:'Plan a local journey',exact:true});
  await expect(task).toBeFocused();await task.check();await page.reload();await expect(task).toBeChecked();
  expect(await page.evaluate(()=>localStorage.getItem('sajilo-nz:predeparture:v1'))).toBeNull();
  await page.getByRole('link',{name:'Saved first-week guides',exact:true}).click();
  await page.getByLabel('Guide language / भाषा').selectOption('ne');
  await page.getByRole('link',{name:'परीक्षण पहिलो हप्ताको यात्रा',exact:true}).click();
  await expect(page.locator('article.guide-body')).toBeVisible();
  await page.route('**/api/guides/**',route=>route.fulfill({json:[]}));
  await context.setOffline(false);
  await expect(page.getByRole('heading',{name:'Guide unavailable in this language'})).toBeVisible();
  await page.getByRole('link',{name:'View saved guides',exact:true}).click();
  await expect(page.getByRole('button',{name:'Remove unavailable guide'})).toBeVisible();
  expect(await page.evaluate(()=>localStorage.getItem('sajilo-nz.saved-guides.v1'))).toBe(oldRecord);
});
