import { navigateSidebar } from './navigation';
import { test, expect } from '@playwright/test';
const key = 'sajilo-nz.saved-guides.v1';
test('search and save persist, refresh offline, complete task offline and remove saved copy', async ({page, context}) => {
  await page.goto('/#/guides');
  await expect(page.locator('.offline-status')).toHaveAttribute('data-offline-ready','true');
  await page.getByRole('searchbox').fill('not-a-match');
  await expect(page.getByRole('heading',{name:'No matching guides'})).toBeVisible();
  await page.getByRole('button',{name:'Clear search'}).click();
  await page.getByRole('searchbox').fill('TRAVEL documents');
  await page.getByRole('link',{name:'Test travel documents'}).click();
  await page.getByRole('button',{name:'Save guide',exact:true}).click();
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).items[0].guide.verified_on,key);
  await context.setOffline(true); await page.reload();
  await expect(page.getByText('This guide exists only in an isolated test database.')).toBeVisible();
  await expect(page.getByText('Showing saved copies only.',{exact:false})).toBeVisible();
  await expect(page.getByText('This is not a new review date.',{exact:false})).toBeVisible();
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).items[0].guide.verified_on,key)).toBe(before);
  await page.getByRole('link',{name:'Passport',exact:true}).click();
  await page.getByRole('checkbox',{name:'Passport',exact:true}).check();
  await page.reload(); await expect(page.getByRole('checkbox',{name:'Passport',exact:true})).toBeChecked();
  await navigateSidebar(page, 'Saved resources');
  await page.getByRole('link',{name:'Test travel documents'}).click();
  await page.getByRole('button',{name:'Remove saved guide'}).click();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Guide unavailable in this language'})).toBeVisible();
  const urls = await page.evaluate(async () => (await Promise.all((await caches.keys()).map(async key => (await (await caches.open(key)).keys()).map(request => request.url)))).flat());
  expect(urls.some(url => url.includes('/api/') || url.includes('/admin/'))).toBe(false);
});
test('reconnect removes withdrawn content while retaining a removable bookmark', async ({page,context}) => {
  await page.goto('/#/guides/test-documents');
  await page.getByRole('button',{name:'Save guide',exact:true}).click();
  await page.route('**/api/guides/**', route => route.fulfill({json:[]}));
  await context.setOffline(true); await context.setOffline(false);
  await expect(page.getByRole('heading',{name:'Guide unavailable in this language'})).toBeVisible();
  await navigateSidebar(page, 'Saved resources');
  await expect(page.getByText('This guide is no longer available.',{exact:false})).toBeVisible();
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).items[0].guide,key)).toBeNull();
  await page.getByRole('button',{name:'Remove unavailable guide'}).click();
  await page.reload(); await expect(page.getByRole('button',{name:'Remove unavailable guide'})).toHaveCount(0);
});
test('storage failures show no false save confirmation and language never falls back', async ({page}) => {
  await page.goto('/#/guides/test-documents');
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Full','QuotaExceededError'); }; });
  await page.getByRole('button',{name:'Save guide',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Could not save changes');
  await expect(page.getByRole('button',{name:'Remove saved guide'})).toHaveCount(0);
  await page.reload(); await page.getByRole('button',{name:'Save guide',exact:true}).click();
  await page.getByLabel('Guide language / भाषा').selectOption('ne');
  await expect(page.getByRole('heading',{name:'Guide unavailable in this language'})).toBeVisible();
  await page.getByRole('link',{name:'View saved guides'}).click();
  await expect(page.getByRole('heading',{name:'No saved guides in this language'})).toBeVisible();
});

test('Nepali offline copy keeps its review dates and progress independently of English', async ({page, context}) => {
  test.setTimeout(60_000); // Several deliberate offline request timeouts on both viewports.
  await page.goto('/#/guides/test-bilingual-documents');
  await expect(page.locator('.offline-status')).toHaveAttribute('data-offline-ready','true');
  await page.getByRole('button', {name:'Save guide', exact:true}).click();
  await expect(page.getByRole('button', {name:'Remove saved guide'})).toBeVisible();
  await page.getByLabel('Guide language / भाषा').selectOption('ne');
  await page.getByRole('button', {name:'Save guide', exact:true}).click();
  await expect(page.getByRole('button', {name:'Remove saved guide'})).toBeVisible();
  const before = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).items, key);
  expect(before).toHaveLength(2);
  const nepali = before.find((item: {language:string}) => item.language === 'ne').guide;
  const english = before.find((item: {language:string}) => item.language === 'en');
  expect(nepali.verified_on).not.toBe(english.guide.verified_on);

  await context.setOffline(true);
  await page.reload();
  await expect(page.locator('article.guide-body')).toHaveAttribute('lang', 'ne');
  await expect(page.getByText(nepali.body, {exact:true})).toBeVisible();
  await expect(page.getByText(english.guide.body, {exact:true})).toHaveCount(0);
  await expect(page.getByText('Showing saved copies only.', {exact:false})).toBeVisible();
  await expect(page.getByText('This is not a new review date.', {exact:false})).toBeVisible();
  await expect(page.locator('article.guide-body time').nth(0)).toHaveAttribute('datetime', nepali.verified_on);
  await expect(page.locator('article.guide-body time').nth(1)).toHaveAttribute('datetime', nepali.next_review_on);
  await page.getByRole('link', {name:'Passport', exact:true}).click();
  await page.getByRole('checkbox', {name:'Passport', exact:true}).check();
  await page.reload();
  await expect(page.getByRole('checkbox', {name:'Passport', exact:true})).toBeChecked();

  await navigateSidebar(page, 'Saved resources');
  await page.getByLabel('Guide language / भाषा').selectOption('ne');
  await page.getByRole('link', {name:'परीक्षण यात्रा कागजात', exact:true}).click();
  await page.getByRole('button', {name:'Remove saved guide'}).click();
  await page.reload();
  await expect(page.getByRole('heading', {name:'Guide unavailable in this language'})).toBeVisible();
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).items, key)).toEqual([english]);
  await page.getByLabel('Guide language / भाषा').selectOption('en');
  await expect(page.getByText(english.guide.body, {exact:true})).toBeVisible();
});
